# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install nodejs and angular-cli
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm install -g @angular/cli

      # Install required dependencies to build app
      - name: Install dependencies
        run: npm ci

      # Build app
      - name: Build app with ng cli
        run: npm build
      
      # deploy app
      - name: Deploy app
        run: echo test...
    
